language: node_js
node_js:
  - lts/*
before_install:
  - export TZ='Asia/Shanghai'

install:
  - npm install hexo-cli -g
  - npm install
script:
  - hexo clean
  - hexo generate
after_script:
  - cd ./public
  - git init
  - git config user.name "IHHRI"
  - git config user.email "476254209@qq.com"
  - git add .
  - git commit -m "Travis CI Auto Builder at $(date +'%Y-%m-%d %H:%M:%S')"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master
branches:
  only:
    - gh-pages
env:
 global:
   - GH_REF: github.com/IHHRI/IHHRI.github.io.git
